version: 2
jobs:
  build:
    working_directory: ~/circleci-demo-python-flask
    docker:
      - image: circleci/python:3.8.0
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.8/site-packages
      - run:
          command: |
            pip install --upgrade pip
            pip install flask
            pip install flask-wtf
            pip install email_validator
            pip install --user flask-sqlalchemy
            pip install flask-bcrypt
            pip install flask-login
            pip install Pillow
            pip install flask-mail
            pip install flask-migrate
      - run:
          command: |
            cd TwojKomputerowiec
            python testyModeli.py
destination: tr1
