"""empty message

Revision ID: b97bc57e6556
Revises: 
Create Date: 2021-05-18 19:36:30.618360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b97bc57e6556'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aktualnosc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tytul', sa.String(length=100), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('tresc', sa.Text(), nullable=False),
    sa.Column('zdjecie', sa.String(length=20), nullable=True),
    sa.Column('videoUrl', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('galeria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tytul', sa.String(length=100), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('zdjecie', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produkt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tytul', sa.String(length=100), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('tresc', sa.Text(), nullable=False),
    sa.Column('zdjecie', sa.String(length=20), nullable=True),
    sa.Column('ilosc', sa.Integer(), nullable=True),
    sa.Column('cena', sa.Float(), nullable=True),
    sa.Column('cyfrowy', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uzytkownik',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('zdjecie', sa.String(length=20), nullable=False),
    sa.Column('haslo', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tytul', sa.String(length=100), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('tresc', sa.Text(), nullable=False),
    sa.Column('uzytkownik_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['uzytkownik_id'], ['uzytkownik.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zamowienie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uzytkownik_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('ukonczone', sa.Boolean(), nullable=True),
    sa.Column('platnosc', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['uzytkownik_id'], ['uzytkownik.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adres_dostawy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uzytkownik_id', sa.Integer(), nullable=False),
    sa.Column('zamowienie_id', sa.Integer(), nullable=False),
    sa.Column('adres', sa.String(length=200), nullable=True),
    sa.Column('miasto', sa.String(length=100), nullable=True),
    sa.Column('kod', sa.String(length=50), nullable=True),
    sa.Column('numer', sa.String(length=100), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uzytkownik_id'], ['uzytkownik.id'], ),
    sa.ForeignKeyConstraint(['zamowienie_id'], ['zamowienie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('obiekt_zamowienia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produkt_id', sa.Integer(), nullable=False),
    sa.Column('zamowienie_id', sa.Integer(), nullable=False),
    sa.Column('ilosc', sa.Integer(), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['produkt_id'], ['produkt.id'], ),
    sa.ForeignKeyConstraint(['zamowienie_id'], ['zamowienie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('obiekt_zamowienia')
    op.drop_table('adres_dostawy')
    op.drop_table('zamowienie')
    op.drop_table('post')
    op.drop_table('uzytkownik')
    op.drop_table('produkt')
    op.drop_table('galeria')
    op.drop_table('aktualnosc')
    # ### end Alembic commands ###
